### ISSUE TITLE
what is the oral.html, acting as the html_path

### ISSUE THREAD

**Issue by rrryan2016** [SilenceEagle/paper_downloader#17]
Thanks for your kind sharing. 

I intend to run the code to download paper of ICLR 2021, but I get confused about the `html_path` in https://github.com/SilenceEagle/paper_downloader/blob/c742c1bd51f059394cd0b294949274b30a54e87b/code/paper_download_ICLR_IDM.py#L644. 

Any suggestion on it? Thanks in advance.

**Comment by SilenceEagle** [comment]
@rrryan2016 
Hi, the *html_path* is the path of a 'html' file, I wrote this function in this way because the link speed to OPENREVIEW in my home is very slow. So I first get the website's html code and then use it to download ICLR papers.
The attached files "oral.txt" and "spotlight.txt" are ICLR 2021 web html code, you can just change the file extension of them from "txt" to "html", and then set the *html_path* to the html file full pathname, such as "F:\oral.html".
In addition, this function could download all the "oral", "spotlight" and 'poster' papers listed in html file, you can use the "oral.html" to download all ICLR2021 oral and poster papers, and use "spotlight.html" to download ICLR2021 spotlight papers
[oral.txt](https://github.com/SilenceEagle/paper_downloader/files/5925848/oral.txt)
[spotlight.txt](https://github.com/SilenceEagle/paper_downloader/files/5925851/spotlight.txt)

**Comment by rrryan2016** [comment]
> @rrryan2016
> Hi, the _html_path_ is the path of a 'html' file, I wrote this function in this way because the link speed to OPENREVIEW in my home is very slow. So I first get the website's html code and then use it to download ICLR papers.
> The attached files "oral.txt" and "spotlight.txt" are ICLR 2021 web html code, you can just change the file extension of them from "txt" to "html", and then set the _html_path_ to the html file full pathname, such as "F:\oral.html".
> In addition, this function could download all the "oral", "spotlight" and 'poster' papers listed in html file, you can use the "oral.html" to download all ICLR2021 oral and poster papers, and use "spotlight.html" to download ICLR2021 spotlight papers
> [oral.txt](https://github.com/SilenceEagle/paper_downloader/files/5925848/oral.txt)
> [spotlight.txt](https://github.com/SilenceEagle/paper_downloader/files/5925851/spotlight.txt)

Thanks for the reply, and it is really helpful. 

But I later get stuck by another error 😄 

`[WinError 2] 系统找不到指定的文件。`  for every paper to download. 

Any suggestion for it, sorry for disturbance.

**Comment by SilenceEagle** [comment]
> > @rrryan2016
> > Hi, the _html_path_ is the path of a 'html' file, I wrote this function in this way because the link speed to OPENREVIEW in my home is very slow. So I first get the website's html code and then use it to download ICLR papers.
> > The attached files "oral.txt" and "spotlight.txt" are ICLR 2021 web html code, you can just change the file extension of them from "txt" to "html", and then set the _html_path_ to the html file full pathname, such as "F:\oral.html".
> > In addition, this function could download all the "oral", "spotlight" and 'poster' papers listed in html file, you can use the "oral.html" to download all ICLR2021 oral and poster papers, and use "spotlight.html" to download ICLR2021 spotlight papers
> > [oral.txt](https://github.com/SilenceEagle/paper_downloader/files/5925848/oral.txt)
> > [spotlight.txt](https://github.com/SilenceEagle/paper_downloader/files/5925851/spotlight.txt)
> 
> Thanks for the reply, and it is really helpful.
> 
> But I later get stuck by another error 😄
> 
> `[WinError 2] 系统找不到指定的文件。` for every paper to download.
> 
> Any suggestion for it, sorry for disturbance.

Have you installed the "Internet Download Manager" software, this function will call IDM to download papers in default setting.
After installing IDM, you can change the setting-->download menu as follow to disable the popup of downloading pages for convenience.
![image](https://user-images.githubusercontent.com/28215838/106986056-8430fd80-67a5-11eb-8744-5b0b254ba8a3.png)
![image](https://user-images.githubusercontent.com/28215838/106986097-9f037200-67a5-11eb-9b0d-b224a9552b1b.png)

If you change the IDM's install path, you should also change this code https://github.com/SilenceEagle/paper_downloader/blob/be6cb67aaff607c4adfaeb298498c926bfb451a7/lib/IDM.py#L13
